apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: mysql-pod
      labels:
        env: testing
        app: mysql-pod
    spec:
      containers:
      - name: mysql-pod
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "false"
        ports:
        - containerPort: 3306
          name: mysql
